"""
Step 7: Builder Agent – implements backend logic, APIs, data models.
Port: 5002
"""
import subprocess
import sys
import uuid
from pathlib import Path

SWARM_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SWARM_ROOT))

from agents.base_agent import BaseAgent
from swarm_config import PROJECTS_DIR


class BuilderAgent(BaseAgent):
    def __init__(self):
        super().__init__(name="builder", port=5002)

    def handle_task(self, task: dict) -> str:
        description = task.get("description", "")
        project_path = task.get("project_path", "")
        self.log(f"Build task: {description}")

        project_name = Path(project_path).name if project_path else f"project_{uuid.uuid4().hex[:6]}"
        src_dir = PROJECTS_DIR / project_name / "src"
        src_dir.mkdir(parents=True, exist_ok=True)

        # Also create tests dir
        tests_dir = PROJECTS_DIR / project_name / "tests"
        tests_dir.mkdir(parents=True, exist_ok=True)

        slug = description.lower().replace(" ", "_")[:30]
        src_file = src_dir / f"{slug}.py"

        lock = self.acquire_lock(str(src_file))
        try:
            src_content = self._generate_module(description)
            src_file.write_text(src_content, encoding="utf-8")
            self.log(f"Wrote source file: {src_file}")

            # Write a basic test stub
            test_file = tests_dir / f"test_{slug}.py"
            if not test_file.exists():
                test_file.write_text(self._generate_test_stub(slug, description), encoding="utf-8")
        finally:
            self.release_lock(lock)

        # Signal verifier
        self._notify_verifier(project_path or str(PROJECTS_DIR / project_name))

        return f"Source created at {src_file}"

    def _generate_module(self, description: str) -> str:
        title = description.strip().title()
        return f'''"""
{title}
Generated by Ultron Builder Agent.
TODO: Implement the actual logic below.
"""


def main():
    """Entry point for: {description}"""
    raise NotImplementedError("Implement me: {description}")


if __name__ == "__main__":
    main()
'''

    def _generate_test_stub(self, slug: str, description: str) -> str:
        return f'''"""Tests for {description}"""
import pytest


def test_{slug}_placeholder():
    """Placeholder – replace with real tests."""
    assert True
'''

    def _notify_verifier(self, project_path: str) -> None:
        import httpx
        from swarm_config import AGENT_PORTS
        try:
            httpx.post(
                f"http://127.0.0.1:{AGENT_PORTS['verifier']}/assign_task",
                json={"description": "Run tests after build change", "project_path": project_path},
                timeout=5.0,
            )
        except Exception as e:
            self.log(f"Could not notify verifier: {e}", "warning")


if __name__ == "__main__":
    BuilderAgent().start()
