"""
Step 6: Designer Agent – creates HTML/CSS/JS UI components.
Port: 5001
"""
import sys
import time
import uuid
from pathlib import Path

SWARM_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SWARM_ROOT))

from agents.base_agent import BaseAgent
from swarm_config import PROJECTS_DIR


class DesignerAgent(BaseAgent):
    def __init__(self):
        super().__init__(name="designer", port=5001)

    def handle_task(self, task: dict) -> str:
        description = task.get("description", "")
        project_path = task.get("project_path", "")
        self.log(f"Design task: {description}")

        project_name = Path(project_path).name if project_path else f"project_{uuid.uuid4().hex[:6]}"
        design_dir = PROJECTS_DIR / project_name / "design"
        design_dir.mkdir(parents=True, exist_ok=True)

        # Generate a basic HTML scaffold
        slug = description.lower().replace(" ", "_")[:30]
        html_file = design_dir / f"{slug}.html"

        lock = self.acquire_lock(str(html_file))
        try:
            html_content = self._generate_html(description)
            html_file.write_text(html_content, encoding="utf-8")
            self.log(f"Wrote design file: {html_file}")
        finally:
            self.release_lock(lock)

        # Signal verifier
        self._notify_verifier(project_path or str(PROJECTS_DIR / project_name))

        return f"Design created at {html_file}"

    def _generate_html(self, description: str) -> str:
        title = description.strip().title()
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <style>
    /* Generated by Ultron Designer Agent */
    body {{ font-family: system-ui, sans-serif; margin: 0; padding: 2rem; background: #0f0f0f; color: #e0e0e0; }}
    .container {{ max-width: 960px; margin: auto; }}
    h1 {{ color: #7c3aed; }}
  </style>
</head>
<body>
  <div class="container">
    <h1>{title}</h1>
    <p><!-- TODO: implement {description} --></p>
  </div>
</body>
</html>
"""

    def _notify_verifier(self, project_path: str) -> None:
        import httpx
        from swarm_config import AGENT_PORTS
        try:
            httpx.post(
                f"http://127.0.0.1:{AGENT_PORTS['verifier']}/assign_task",
                json={"description": "Run tests after design change", "project_path": project_path},
                timeout=5.0,
            )
        except Exception as e:
            self.log(f"Could not notify verifier: {e}", "warning")


if __name__ == "__main__":
    DesignerAgent().start()
